/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTRATION_H_RPCGEN
#define _REGISTRATION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Student {
	int regNum;
	char *name;
};
typedef struct Student Student;

#define REGISTRATION 0x30000001
#define REGISTRATION_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER 1
extern  int * register_1(Student *, CLIENT *);
extern  int * register_1_svc(Student *, struct svc_req *);
extern int registration_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER 1
extern  int * register_1();
extern  int * register_1_svc();
extern int registration_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Student (XDR *, Student*);

#else /* K&R C */
extern bool_t xdr_Student ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTRATION_H_RPCGEN */
